version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.8.1
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action_server:
    image: htmercury/nlp-rasa
    volumes:
      - ./actions:/app/actions